# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

#Sanctuary
Location.create(name:"Aotea Great Barrier",description:"Great Barrier Island (GBI) is an island lying some 100 kilometers (62 miles) northeast of central Auckland in the outer Hauraki Gulf of the North Island of New Zealand. Known as “Aotea” to the indigenous Māori people, it is the sixth-largest island of New Zealand. Aotea/Great Barrier Island is the first island in the world to receive International Dark Sky Sanctuary status. The Milky Way spans the Southern Hemisphere sky and the Magellanic Clouds, not visible in the Northern Hemisphere, are easily seen. The night sky is woven into Maori culture with Matariki, the rise of the Pleiades constellation, signalling the Maori New Year. The night sky is a sight residents already share with visitors but the spectacular nature of the Island sky deserves to be shared with the world.",latitude:-36.2075,longitude: 33.47645 ,category:"Dark Sky Sanctuary",rating:5.0,image:"https://www.darksky.org/wp-content/uploads/2017/06/GBI-app-page-56-768x402.png",area:"285 km2",country:"Great Barrier Island,New Zealand")

Location.create(name:"Cosmic Campground",description:"The Cosmic Campground is a 1.42 hectare (3.5 acre) site in the Gila National Forest of western New Mexico, U.S. Situated between the Gila Wilderness and the Blue Range Primitive Area, it is located on land managed by the United States Forest Service. The Campground is located in an exceptionally dark part of the lower 48 U.S. states, with the nearest significant source of artificial light more than 65 kilometers away across the state line in Arizona. The Campground features a very basic infrastructure to support campers and offers a 360-degree, unobstructed, view of the night sky.",latitude:-108.9228668,longitude: 33.47994614 ,category:"Dark Sky Sanctuary",rating:4.5,image:"https://www.darksky.org/wp-content/uploads/2016/01/CC_MilkyWay.png",area:"0.01 km2",country:"New Mexico, United States")

Location.create(name:"Devils River State Natural Area",description:"Devils River State Natural Area offers a variety of water activities on the beautiful Devils River. Fed by numerous clear springs, Devils River is not only ecologically intact, it is an excellent fishing location. But, more importantly, this isolated natural beauty offers quiet dark night skies complemented by the rushing untamed sound of the Devils River.",latitude: 29.939694,longitude: -100.970206 ,category:"Dark Sky Sanctuary",rating:4.5,image:"https://www.vacationsmadeeasy.com/images/TheBLT/x1882.jpg.pagespeed.ic.z_CCsDl1NI.jpg",area:"80.88 km2",country:"Texas, United States")

Location.create(name:"Gabriela Mistral",description:'Located in Northern Chile, the Elqui Valley, has ideal stargazing conditions. At an Altitude of some 2,900m and with a temperate climate, the fourth region of Chile, in which this valley can be found, provides the perfect setting for extraordinarily clear skies.
The skies at night are so perfect, in fact, that it’s more than just stars that spectators can witness. The planets can be seen clearly – even with the naked eye.
As for the constellations, they are almost all visible except the [Ursa Major], which can only be seen in the Northern Hemisphere.',latitude: -30.16972,longitude: -70.80639 ,category:"Dark Sky Sanctuary",rating:5.0,image:"https://www.businessdestinations.com/wp-content/uploads/2018/02/Astrotourism.jpg",area:"364 km2",country:"Elqui Valley, Chile")

Location.create(name:"Rainbow Bridge National Monument",description:'Rainbow Bridge National Monument is a 65-hectare (160 acre) site in the U.S. state of Utah that preserves one of the tallest and longest natural bridges in the world. The bridge was created by Bridge Creek during the last glacial period, during which it encountered layers of sandstone of different durability deposited in the area during an extended arid period during the Triassic and Jurassic geologic eras. The water diverted around what became the bridge after eroding away softer rocks from the harder sandstone beneath them. Continuous washing of the creek water, containing abrasive quartz grains, against each side of the turn eventually eroded a continuous passage through its center.
The bridge, of cultural importance to a number of area Native American tribes, has been designated a Traditional Cultural Property by the U.S. National Park Service. Evidence of human habitation in the area extends back at least a thousand years; the modern Pauite and Navajo people came to call the structure Nonnezoshe or “rainbow turned to stone.” Nearby inhabitants continue to revere the bridge as a sacred place. Due to its extremely remote location in difficult terrain, the existence of the bridge was not known to European-Americans until 1909.Its remote setting has also kept Rainbow Bridge well away from later European settlement; to this day, it is only accessible via a two-hour boat ride on Lake Powell from marinas near Page, Arizona, followed by a mile-long hike, or by hiking overland for several days from a trailhead on the south side of Lake Powell. As a result, the site remains naturally dark; the U.S. National Park Service Natural Sounds and Night Skies Division estimates that artificial light at the zenith is less than five percent above the natural background level. Given the Monument’s protected status and isolated location, and taking into account its essentially pristine night skies, it is especially appropriate to the International Dark Sky Sanctuary label.',latitude: 37.07514 ,
longitude: -110.9644 ,category:"Dark Sky Sanctuary",rating:5.0,image:"https://www.darksky.org/wp-content/uploads/2018/03/RABR-feat-700px-366px.png",area:"0.65 km2",country:"Utah, United States")

Location.create(name:"Stewart Island / Rakiura",description:"Stewart Island-Rakiura lies at the extreme Southern tip of New Zealand and boasts a modest 390 residents. New Zealand’s 3rd largest island by land area, 85% of Stewart Island is formally protected as the Rakiura National Park. Owing to the island’s remoteness and sparse population, Stewart Island/Rakiura’s exceptionally dark skies are a wonder to experience.",latitude:-46.9973,longitude: 167.8372 ,category:"Dark Sky Sanctuary",rating:5.0,image:"https://resources.stuff.co.nz/content/dam/images/1/s/d/i/4/3/image.related.StuffLandscapeSixteenByNine.1420x800.1s1oed.png/1543672398144.jpg",area:"1,746 km2",country:"Stewart Island,New Zealand")

#Reserves
Location.create(name:"Aoraki Mackenzie",description:"The Aoraki Mackenzie International Dark Sky Reserve is comprised of Aoraki/Mt. Cook National Park and the Mackenzie Basin of New Zealand’s South island. Outdoor lighting controls were first put into place in the area during the early 1980s. They have not only helped minimize light pollution for the nearby Mt. John Observatory, but also conserve energy, protect wildlife and make the area a popular stargazing destination for tourists.
The natural night has played a critical role in the areaʼs history as its first residents, the Māori, not only used the night sky to navigate to the island but also integrated astronomy and star lore into their culture and daily lives. The reserve seeks to honor that history by keeping the night sky a protected and integral part of the areaʼs natural and cultural landscape. It is a perfect place to protect and honor those traditions as the reserveʼs Mackenzie Basin has the clearest, darkest and the most spectacular night sky in New Zealand.",latitude:-43.99528,longitude:170.46139,category:"Dark Sky Reserve",rating:4.0,image:"https://www.darksky.org/wp-content/uploads/2015/01/Crux_and_Church_aoraki.jpg",area:"4,367 km2",country:"New Zealand")

Location.create(name:"Brecon Beacons National Park",description:"Brecon Beacons National Park is situated in a part of south Wales where sheep outnumber people 30 to 1. A secluded utopia for stargazing and appreciating the natural nighttime environment, the Dark Sky Reserve is home to some 33,000 residents and is within easy access of over a million people. The park has gone to great lengths in replacing lighting that used to make it difficult to see the majestic night sky and continues to work toward making 100 percent of lighting within the reserve’s core zone dark sky friendly. Communities within the reserve have been responsive and attentive to the cause, helping to keep the night sky pristine for future generations.",latitude:51.88333 ,longitude:-3.4,category:"Dark Sky Reserve",rating:3.8,image:"https://www.darksky.org/wp-content/uploads/2015/01/Brecon_Beacons_sinclair.jpg",area:"1,347 km2",country:"Wales,United Kingdom")

Location.create(name:"Central Idaho",description:"The Central Idaho Dark Sky Reserve is a region of 3,668 square kilometers (1,416 square miles) of remote and largely rugged lands in the Sawtooth Mountains of central Idaho, U.S. The Reserve has as its core parts of two recognized wilderness areas, and is situated in the spectacular scenery of the Sawtooth National Forest. In addition to the world-class skiing in the Sun Valley area, visitors come to the area for day hiking, backpacking, and horseback riding and accessed from 23 major trailheads.The Reserve’s chief draw is its wilderness quality, with its lack of development and significant visitor services. It remains among a shrinking number of places in the lower 48 United States where visitors can have a truly ‘off-grid’ experience, with access to neither electricity nor mobile phone service across thousands of square kilometers. As the challenging topography of the Sawtooth Range has historically discouraged the development of significant infrastructure, so the land has largely resisted electrification leading to the deployment of large amounts of artificial light at night. Central Idaho is therefore one of the last large ‘pools’ of natural nighttime darkness left in the United States. Administrators of the public lands in this region find dark skies congruent with the management philosophy of natural wilderness, and a nascent astrotourism industry is building in the area to cater to visitors who come to see the near-pristine night skies over the Sawtooth.",latitude:43.96239,longitude:-114.91222,category:"Dark Sky Reserve",rating:4.3,image:"https://www.darksky.org/wp-content/uploads/2017/12/StanleyLake-feat-700px-366px.png",area:"3,668 km2",country:"Idaho,United States")

Location.create(name:"Cévennes National Park",description:"Cévennes National Park, or ‘Parc National des Cévennes’ in French, is a 2,973-square-kilometer national park situated mainly in the sparsely populated French départements of Lozère, Gard, Ardèche and Aveyron. The region is located in the southeastern extreme of the Massif Central, a highland region of mountains and plateaus in the middle of southern France. The land rises above the plains of the Languedoc region and slopes gradually toward the Mediterranean Sea in a series of plains alternating with a maze of deep river valleys. The park includes several mountains and high plateau including Mont Lozère, Mont Aigoual and the Causse Méjean.
Occupied by humans for at least the last 400,000 years, Cévennes is best known as the heart of the Camisard revolt of the early eighteenth century, in which French Calvinist Protestants rose up against religious persecutions following the Edict of Fontainebleau, issued by King Louis XIV in 1685. Despite its rebellious past, today Cévennes is the peaceful home of over 71,000 inhabitants living in 250 villages within its borders. They operate over 400 farms whose lands comprise one quarter of the park’s territory. It is, as National Geographic puts it, “not a pure wilderness park but a classic landscape of traditional French life.” The Park offers a diversity of outdoor activities such as hiking, mountain biking, fishing, kayaking, and spelunking.
The rugged landscape and traditionally difficult life of the typical cévenol throughout history has largely kept development at bay, and the Park remains one of the darker spots in southern France. Visitors to the region increasingly come to view the night sky, largely unspoiled by skyglow as in the more densely populated regions of the country. The Park authority has done a commendable job in developing this resource carefully for the benefit of both public outreach as well as sustainable tourism.",latitude:44.22819,longitude:3.71833,category:"Dark Sky Reserve",rating:4.0,image:"https://www.darksky.org/wp-content/uploads/2018/08/Mont-Lozere-G-Cannat-feat-700px-366px.png",area:"3,600 km2",country:"France(southern)")

Location.create(name:"Exmoor National Park",description:"Located in the southwest of England in Somerset and Devon Counties, Exmoor National Park enjoys the darkest skies in the country yet offers relatively easy access from urban hubs. Many who have settled within the park’s boundary associate Exmoor’s dark nights with a high quality of life and an unpolluted night sky contributes significantly to this atmosphere. Dark sky awareness in the park bloomed in 2009 with a variety of programs on astronomy and conservation held during UNESCO’s International Year of Astronomy.",latitude:51.12754 ,longitude:-3.65,category:"Dark Sky Reserve",rating:3.4,image:"https://www.darksky.org/wp-content/uploads/2015/01/vfilms-exmoor.jpg",area:"181 km2",country:"England,United Kingdom")

Location.create(name:"Kerry",description:"Kerry International Dark Sky Reserve sits on the Iveragh Peninsula, home to nearly 4,000 residents, and incorporates approximately 700 square km of territory along the Wild Atlantic Way tourism trail. Its location between the Kerry Mountains and the Atlantic Ocean provides some natural protection against light pollution. The night sky has captivated the people of Ireland for millennia. Nearly 6,000 years ago, the Neolithic inhabitants of the Iveragh Peninsula built stone monuments incorporating alignments to track cycles of the Sun, Moon, and stars. According to some experts, ancient Ogham-language inscriptions found in the region may depict celestial observations.",latitude:51.82623,longitude:-10.17472,category:"Dark Sky Reserve",rating:3.7,image:"https://www.darksky.org/wp-content/uploads/2015/01/kerry_skelligs.jpg",area:"700 km2",country:"Ireland")

Location.create(name:"Mont-Mégantic",description:"Nestled deep in the heart of Mont-Mégantic National Park in the Eastern Townships of Quebec, ASTROLab is the world’s first International Dark Sky Reserve. A true hidden gem, it is arguably one of the most awe-inspiring places in Canada -- the kind that stops you in your tracks and sparks deep thought and reflection. At the two observatories, visitors get a chance to admire ancient stars, enchanting planets and even the northern lights if luck strikes.",latitude:45.45543,longitude:-71.1625,category:"Dark Sky Reserve",rating:4.4,image:"https://ssl.tzoo-img.com/images/tzoo.14993.0.709387.Darksky.jpg?width=1280&spr=2",area:"5,300 km2",country:"Québec,Canada")

Location.create(name:"Moore's Reserve",description:"Not all of the best places to stargaze are isolated. Just an hour south of London is Moore’s Reserve at South Downs National Park, known for its white chalk cliffs and 18th-century Halnaker Windmill. England’s newest national park (designated in 2011) had its first Dark Skies Festival in February, complete with astronomer-hosted “star parties” that include telescopes open for use. This dark area between London and the southern coast of England is one of very few such places left in the country.",latitude:-33.9821,longitude:151.0874,category:"Dark Sky Reserve",rating:3.6,image:"https://www.darksky.org/wp-content/uploads/2016/05/HalnakerWindmill-700px-366px.png",area:"1,627 km2",country:"South Downs,England")

Location.create(name:"NamibRand Nature Reserve",description:"Namibiaʼs NamibRand Nature Reserve, one of Africaʼs largest private nature reserves, lies in one of the naturally darkest (yet accessible) places on Earth. It was established to help protect and conserve the unique ecology and wildlife of the southwest Namib Desert, and its mission now includes preservation of the area’s starry night skies.",latitude:-25.0,longitude:16.0,category:"Dark Sky Reserve",rating:5.0,image:"https://www.smartertravel.com/uploads/2017/05/NamibRand2.jpg",area:"2,022 km2",country:"Namibia")

Location.create(name:"Pic du Midi",description:"The highest Dark-Sky Reserve you can visit, Pic du Midi sits above the clouds in the French Pyrenees Mountains. It may sound and look like an astronomer-only facility, but it welcomes overnight visitors for “star parties” and even traditional local food offerings. Take the cable car up on a clear day for far-flung views of the snow-capped mountains before turning your eyes to the golden sunset and starry night sky.",latitude:42.93638,longitude:-0.14139,category:"Dark Sky Reserve",rating:4.0,image:"https://www.darksky.org/wp-content/uploads/2015/01/picdumidi-compere.jpg",area:"3,112 km2",country:"France")

Location.create(name:"Rhön",description:"This biosphere reserve established by UNESCO is known as the “land of endless horizons”. Its starry skies have IDA’s Silver Tier-status and have clear views of the Milky Way and Andromeda galaxy with the naked eye. The darkest nights are at the core of the reserve, which is home to nearly two lakh residents that use sustainable outdoor lighting at night. A non-profit at Sternenpark Rhoen offers guided stargazing and night walks.",latitude:50.56087,longitude:10.07861,category:"Dark Sky Reserve",rating:4.0,image:"https://www.darksky.org/wp-content/uploads/2015/01/Star_trails_Wasserkuppe_Werner_Klug_Rhon.jpg",area:"1,720 km2",country:"Germany")

Location.create(name:"Snowdonia National Park",description:"Snowdonia National Park is the first UK National Park named in Wales, sprawling over more than 2,100 square kilometers of territory – some ten percent of the total land area of Wales. The Park’s name traditionally applied to a smaller, upland area of northern Gwynedd around Snowdon mountain, while the Park includes a land area more than twice that size and extending to the south well into the region of Meirionnydd. The terrain of Snowdonia largely consists of the mountainous lands that run the length of Wales, although its lower reaches extend into coastal areas. The rugged interior of the Park supports little human settlement to this day, and consequently has created a naturally dark haven separate from coastal cities. Along with Dark Sky Parks Brecon Beacons National Park and the Elan Valley Estate to its south, Snowdonia is among the darkest places remaining in southern Britain.",latitude:52.90415,longitude:-3.86383,category:"Dark Sky Reserve",rating:3.8,image:"https://www.darksky.org/wp-content/uploads/2015/11/Llyn_Llydaw_Snowdonia_700px-366px.png",area:"2,132 km2",country:"Wales,United Kingdom")

Location.create(name:"Westhavelland",description:"Westhavelland Nature Park is the largest protected area in the German federal state of Brandenburg and comprises the largest contiguous wetland of any individual European country. The park is situated only 70 km west of Berlin, the most populous city in Germany, yet its sparse population and protected status put the experience of a dark night sky within easy reach of nearly six million people in the Berlin-Brandenburg Metropolitan Region. The Dark Sky Reserve consists of a mix of 750 square kilometers of public and private land within the park.",latitude:52.66797,longitude:12.43333,category:"Dark Sky Reserve",rating:3.8,image:"https://www.darksky.org/wp-content/uploads/2015/01/p1550321.jpg",area:"747.9 km2",country:"Germany")


#Parks
